### ISSUE TITLE
exception 'Exception' with message 'Not a valid token set.' 

### ISSUE THREAD

**Issue by tttp** [cultuurnet/culturefeed#10]
Trying to use the events_cdb module

I have put the key+secret in the config for the application.

exception 'Exception' with message 'Not a valid token set.' in /var/www/.../sites/all/modules/custom/culturefeed/lib/Drupal/DrupalCultureFeedBase.php:98
Stack trace:
#0 /var/www/.../sites/all/modules/custom/culturefeed/lib/Drupal/DrupalCultureFeed_EntryApi.php(49): DrupalCultureFeedBase::getLoggedInUserInstance()
#1 /var/www/.../sites/all/modules/custom/events_cdb/events_cdb.sync.inc(177): DrupalCultureFeed_EntryApi::createEvent(Object(CultureFeed_Cdb_Item_Event))

The user doesn't seem to have any token. Are they supposed to be different than the site/application ones? Is there a way to link them? Is there something to do at the permission level?

You have no idea how hard is it to use a library that isn't documented ;)

**Comment by svenhoutmeyers** [comment]
Sorry we didn't answer this issue for 1,5 year, but now we finally have documentation on https://github.com/cultuurnet/culturefeed (readme) and https://github.com/cultuurnet/culturefeed/wiki.
