### ISSUE TITLE
Drupal 8 status

### ISSUE THREAD

**Issue by TomDeS** [cultuurnet/culturefeed#102]
Are there any plans to continue working on the Drupal 8 branch? Would love to convert our current site to D8.

**Comment by svenhoutmeyers** [comment]
Tom,

We created a branch (https://github.com/cultuurnet/culturefeed/tree/drupal-8) and developed some simple functionalities already, but we have some other project on our roadmap first. However if you have a client who wants to invest we are happy to help of even prioritise de Drupal8 suite. Please mail me (sven @ cultuurnet.be) if you want some more information.

Sven
