### ISSUE TITLE
Location (actor, not region) as Facet

### ISSUE THREAD

**Issue by KevinCoworks** [cultuurnet/culturefeed#108]
Is there a possibility to have location (aka venue / space / etc.) as a facet filter so that a filtering can be done on a specific location for an event search. This is a recurring request from clients and I know this wasn't possible before, but quite some time/changes happened since last time I asked :)

**Comment by stijnswaanen** [comment]
Hi @KevinCoworks 
this is now possible with the filter-form-block in culturefeed_search_ui (https://github.com/cultuurnet/culturefeed/wiki/Culturefeed-Search-UI-Block-Custom-Filters).
In the inputfield for filterquery you could filter on the location id of the specific location.
