### ISSUE TITLE
Exception: Not a valid token set. in DrupalCultureFeedBase::getLoggedInUserInstance()

### ISSUE THREAD

**Issue by zero2one** [cultuurnet/culturefeed#169]
h2. Problem
The `culturefeed_entry_ui` module implements `hook_menu_local_tasks_alter()` to add tabs to collaborate on Culturefeed entries.

The code does not check upfront if the user is logged in and this results in exceptions.
That exception is catched and logged to Drupal watchdog.

```
Exception: Not a valid token set. in DrupalCultureFeedBase::getLoggedInUserInstance() (line 165 of contrib/culturefeed/lib/Drupal/DrupalCultureFeedBase.php).
```

The exception is triggered on every page load for anonymous users. This results in a flooded log.

h2. Solution
Check in the `culturefeed_entry_ui_menu_local_tasks_alter()` first if there is a logged in user.

**Comment by zero2one** [comment]
Solution see : 170

**Comment by cyberwolf** [comment]
Hi Peter,

Wouldn't it be better to catch the exception and ignore it, because in this situation it's a valid case?

culturefeed_load_logged_in_user() still writes to the log if an exception occurs, so if you replace  DrupalCultureFeed::getLoggedInUser() with this, your log will still be flooded.

```
function culturefeed_load_logged_in_user() {
  try {
    return DrupalCultureFeed::getLoggedInUser();
  }
  catch (Exception $e) {
    watchdog_exception('culturefeed', $e);
  }
}
```

**Comment by zero2one** [comment]
The code here does not want to check if I'm logged in, it wants to add tabs, for a user with the proper access rights, to  access the Entry API tabs.
So it should first check if it deals with a logged in user before it tries to access methods on a NULL value on 99% of the page loads.

The code is now executed on each page load, also for non logged in users.
This results in tons of log records because the code tries to access unaccessible code…
(We had 40.000 records in 7 days).
