### ISSUE TITLE
Remove all non-generic theming

### ISSUE THREAD

**Issue by pfrenssen** [cultuurnet/culturefeed#17]
The templates contain theming which seems to be intended for a specific theme, and is not applicable to all themes. Users of the module suite are practically forced to override every template file, theme function and even render arrays generated in code.

An example:

```html
      <i class="icon-remove icon-large text-red"></i><span class="hidden">verwijder</span>
```

The classes 'icon-large' and 'text-red' are pointless in most theme implementations and are not semantically correct. In most themes this icon would not be present. The word "verwijder" is not translatable.

Another example, which is in code, also contains an icon which would not exist in most themes and might actively break certain themes because of the 'pull-right':

```php
'#markup' => '<p class="pull-right">' . l('<i class="icon-pencil"></i> ' . t('Manage your actions'), 'culturefeed/activities', array('html' => TRUE, 'attributes' => array('class' => array('manage-activities-link')))) . '</p><div class="clearfix"></div>',
```

**Comment by svenhoutmeyers** [comment]
We moved all non-generic theming to https://github.com/cultuurnet/culturefeed_bootstrap
