### ISSUE TITLE
Many exceptions in watchdog

### ISSUE THREAD

**Issue by Jelle-S** [cultuurnet/culturefeed#195]
We get a lot of these exceptions in our watchdog log:
`Exception: Not a valid token set. in DrupalCultureFeedBase::getLoggedInUserInstance() (regel 160 van [...]\sites\all\modules\contrib\culturefeed\lib\Drupal\DrupalCultureFeedBase.php).`

The cause is `culturefeed_entry_ui_menu_local_tasks_alter`, which tries to load the event, which in turn calls `DrupalCultureFeedBase::getLoggedInUserInstance`, even for anonymous users, resulting in the exception.

**Comment by stijnswaanen** [comment]
see #169

**Comment by stijnswaanen** [comment]
Sorry, I made a release but it was still in draft.
The issue you mentioned is fixed in that relase
