### ISSUE TITLE
Searches with special chars (accents, umlauts) do not yield search results

### ISSUE THREAD

**Issue by KevinCoworks** [cultuurnet/culturefeed#26]
The agenda search block in culturefeed_agenda (with the form generated by culturefeed_agenda_search_block_form) has a problem with searches that contain special characters (like accents and umlauts)

For example:

When searching for the string "Pierre Célice" (agenda/search?search=Pierre%20Célice) no results are found.
When searching for the string "Pierre Celice) (agenda/search?search=Pierre%20Celice) the correct result is found => Pierre Célice - Rhythms en Collages (agenda/e/pierre-celice-rhythms-en-collages/76deead9-b8a5-4a58-b6f5-701c9daf768a)

**Comment by KevinCoworks** [comment]
Any update on this?

**Comment by svenhoutmeyers** [comment]
Hello Kevin, 

We are releasing 3.5 version today which is going to fix this. Sorry that it took so long.

S

**Comment by KevinCoworks** [comment]
I can confirm searches with accents are fixed but none of the terms (search terms, titles and trefwoorden) are displaying umlauts properly at the moment ("?" instead of the umlauted character)

Example: 
Skiën is displayed as Ski?n (and Ski%253Fn) in the titles and trefwoorden

Searching for:
agenda/search?search=skiën 
no results

agenda/search?search=skien
no results

/agenda/search?search=ski%253Fn
Gives the wanted results
