### ISSUE TITLE
Lost required packages in v3.4.1

### ISSUE THREAD

**Issue by cgoffin** [cultuurnet/culturefeed#28]
In v3.4.1 the required packages cultuurnet/search: ~1.0 and cultuurnet/culturefeed-php: ~1.1 are lost.

Because of this the culturefeed_search module doesn't work anymore. Is this the expected behavior after updating?

**Comment by svenhoutmeyers** [comment]
The tag did not pointed to the right commit, excuses. Can you check if it's ok now?

https://github.com/cultuurnet/culturefeed/releases/tag/v3.4.1

**Comment by cgoffin** [comment]
Problem solved. Thank you.
