### ISSUE TITLE
Documentation: "drush cs-it" abbreviation does not work.

### ISSUE THREAD

**Issue by matthiasm11** [cultuurnet/culturefeed#29]
The drush abbreviation "drush cs-it" stated on https://github.com/cultuurnet/culturefeed/wiki/Culturefeed-Search-Views-Filters-Categories does not work. The correct full drush command is "drush culturefeed-search-import-terms".

PS: culturefeed.info still contains version "7.x-3.3" in stead of "7.x-3.4" on the 3.4 branch.

**Comment by stijnswaanen** [comment]
Ok, I just changed the documentation. Thanks for your contribution!
The correct info in culturefeed.info will be in release 3.4.2

**Comment by svenhoutmeyers** [comment]
fixed in https://github.com/cultuurnet/culturefeed/releases/tag/v3.4.2
