### ISSUE TITLE
Make culturefeed module a dependency for culturefeed-agenda

### ISSUE THREAD

**Issue by frankbaele** [cultuurnet/culturefeed#30]
Hi,

I installed the culturefeed-agenda module but but not the base culturefeed module.
This resulted in wsod on agenda search pages with  query parameters.
error:
PHP Fatal error:  Call to undefined function culturefeed_set_noindex_metatag() in /pathToRootOfProject/sites/all/modules/contrib/culturefeed/culturefeed_search_ui/includes/helpers.inc on line 168

Fixed this by enabling the culturefeed base module. 
Since this function was in culturefeed.helpers.inc .

**Comment by Stalski** [comment]
I see a dependency to the culturefeed_search and culturefeed_search_ui module, however the culturefeed_search module should have a dependency to the culturefeed module as well.

**Comment by svenhoutmeyers** [comment]
correct, will fix it in next release

**Comment by svenhoutmeyers** [comment]
fixed in https://github.com/cultuurnet/culturefeed/releases/tag/v3.4.3
