### ISSUE TITLE
culture feed agenda theme facets

### ISSUE THREAD

**Issue by frankbaele** [cultuurnet/culturefeed#31]
Hi,

In the previous version of the culture feed module, there was a "what" facet block(cnapi module). 
This block allowed faceted filtering based on the theme/type of the activities on search pages.
In the current culture feed module I can't seem to find it in code or configuration.

Has this feature been removed? 
If yes, Is it possible to rebuild it myself?

Frank

**Comment by svenhoutmeyers** [comment]
Hi Frank,

It has been replaced by "Culturefeed search: facet Type" block, configurable on /admin/structure/block/manage/culturefeed_search_ui/facet-eventtype/configure (it's on of the facets provided with the categories from our categorisation web service https://github.com/cultuurnet/culturefeed/wiki/Culturefeed-Search-UI-Block-Facet)

If the highest level (Doen, Kijken en luisteren, ...) is irrelevant you can choose to show only the second level.

**Comment by lukdens** [comment]
In addition: 
1. in case you don't see the level configuration for the eventtype facet, be sure to disable the "Compatibility markup" checkbox on ~/admin/config/culturefeed/search-ui
2. there's also a "Culturefeed search: facet Theme" block with a setting to make it only visible when first an eventtype has been chosen. These 2 blocks together will work more or less the same as the cnapi "What" facet block.

**Comment by frankbaele** [comment]
hi,

Thx for the feedback.

But in my local install I have the following results:
1: "Culturefeed search: facet Type" block  retruns only events and no sub items(tried all the hierarchy options).
2: "Culturefeed search: facet Theme" -> cannot find this block in the interface or the code, does this still exist?

**Comment by lukdens** [comment]
1: What settings did you use for this block and for the CultureFeed Search UI module. Then we can try to reproduce this behavior. Normally it should work with both "Compatibility markup" enabled or disabled.
2: When you're in a dutch interface this block is translated to "Culturefeed search: facet Thema". Probably this solves this issue. It's on ~/admin/structure/block/manage/culturefeed_search_ui/facet-theme/configure

Have a look at: http://m.uitinvlaanderen.be/agenda/search
Is this the desired behavior for types and themes?

**Comment by frankbaele** [comment]
ok,

I can view the configuration for the block, but the block itself is not
visible in the block list.

When i look in the hook_block_info (search_ui) i can't find its declaration.

If i add it there manualy, I can add the block to a page, but in a broken
state.

I cloned the latest version from github btw.

**Comment by lukdens** [comment]
Hi Frank

I think I know what's going wrong. This blocks won't show up if there are no terms (types, themes) in your local db. To import all terms you can use command "drush csit". To import all cities, use "drush csic".

See https://github.com/cultuurnet/culturefeed/wiki/Culturefeed-Search-Drush

Hope this will do the trick :-)

Luk

**Comment by lukdens** [comment]
Same for the eventtype block btw. So probably you were looking at the "entity type" block if you only saw "events" in it.

**Comment by frankbaele** [comment]
Ok, 

Thank you for the information, the theme block became visible in the list after doing the drush terms import. Should have imported them first before looking for the filter blocks.

thx
