### ISSUE TITLE
Vliegje

### ISSUE THREAD

**Issue by BertBruggeman** [cultuurnet/culturefeed#47]
Wij kregen de vraag om het “vliegje” te tonen bij zowel de teaser en de detailpagina van een activiteit,
Hoe passen we dit toe, ik zie geen variabele voor het vliegje in de tpl bestanden…

**Comment by lukdens** [comment]
Dag Bert, de variabele die je zoekt heet $forkids en wordt TRUE als de $agefrom kleiner is dan 12 of als het event een keyword "ook voor kinderen" heeft.
