### ISSUE TITLE
Thema in search block

### ISSUE THREAD

**Issue by BertBruggeman** [cultuurnet/culturefeed#48]
De categorieën select box bij de “search events” blok blijft leeg, hoe lossen we dit op?
Ik weet dat we via de “Filter form” blok zelf categoriefilters kunnen toepassen maar dit zou automatisch moeten kunnen…

**Comment by svenhoutmeyers** [comment]
Hallo Bert, heb je de 'terms' geïmporteerd? 

https://github.com/cultuurnet/culturefeed/wiki/Culturefeed-Search-Drush
