### ISSUE TITLE
Robots

### ISSUE THREAD

**Issue by BertBruggeman** [cultuurnet/culturefeed#50]
Na het inschakelen van de modules staat de meta tag meta name="robots" content="noindex, follow" globaal ingesteld op alle pagina's....

**Comment by lukdens** [comment]
Dag Bert, 

het is een bewuste keuze om dit te doen voor alle development omgevingen om te vermijden dat deze geïndexeerd zouden worden door Google en overbodige duplicate content zouden genereren. 

Zodra je op een productie-URL test (zonder "develop", "acc" of "culturefeed" in de URL) en geconnecteerd bent met de productie API (www.uitid.be ipv acc.uitid.be), zou de globale noindex automatisch moeten verdwijnen.

Kan je verifiëren of dit je probleem oplost?

**Comment by BertBruggeman** [comment]
Zou dit dan niet enkel op pagina's dat effectief een culturefeed module aanspreken moeten komen i.p.v. globaal?

**Comment by lukdens** [comment]
Ik denk dat dat klopt ja, maar van zodra je bv. ergens een login block van culturefeed hebt aan staan, zal het dus ook globaal werken. Anderzijds kan je niet-culturefeed pagina's op testomgevingen toch ook beter niet laten indexeren?

**Comment by BertBruggeman** [comment]
Het komt niet veel voor dat ik de culturefeeds moet inschakelen op productie websites, ik let hier in de toekomst op...
