### ISSUE TITLE
Gerelateerde activiteiten

### ISSUE THREAD

**Issue by BertBruggeman** [cultuurnet/culturefeed#51]
Als ik de blok gerelateerde activiteiten inschakel werk deze zoals het moet, zodra ik iets wijzig in het blok form zie ik de ajax lader maar geen activiteiten...

**Comment by svenhoutmeyers** [comment]
Hallo Bert is dit issue al gefixed? Want is me wel een onbekend issue...

S

**Comment by pieterdt** [comment]
issue bestaat nog. Als er geen instellingen zijn gedaan voor de sortering, dan krijgt het settingsformulier daar toch een spatie ingevuld. Als het formulier dan opgeslagen wordt, dan wordt die instelling ' ' opgeslagen, en geeft problemen. Expliciet verwijderen van de spatie vooraleer op te slaan lost het probleem op.

**Comment by stijnswaanen** [comment]
zie PR: https://github.com/cultuurnet/culturefeed/pull/146
