### ISSUE TITLE
Entry API - not working ?

### ISSUE THREAD

**Issue by 30equals** [cultuurnet/culturefeed#52]
Hey hey,

I'm trying out the Entry API Drupal module at the moment without any success.
Started from the master branch and going through the setup as mentioned in the wiki. 
At 'agenda/e/add' i get the 'An error occurred while saving the event' error.

Yes, i have a validated consumer key/secret set, which i entered in the entry api info form.

Because this doesn't work, i tried using the install profile, where i get the exact same error (and more -- i'll document this later). Here i also noticed that the 'develop' branch is checked with the make file...? 

Anyway, i have the impression that it's failing in in culturefeed/lib/Drupal/DrupalCultureFeedBase at line
#156 because the logged in user doesn't have any tokens assigned.

But with the install profile i even logged in with oath, and tried to create an event (yes - i set the right permissions) and still got that same error..

Now, or i am missing something - although i read the full Wiki numerous times, and checked the pages at http://tools.uitdatabank.be/docs/entry-api-content-beheer as well - ?

It would be nice to have my issue validated by the cultuurnet folks - or if you don't come across the same issues, provide a somewhat detailed guide to get this working. 

Thanx!

**Comment by svenhoutmeyers** [comment]
Hello Jim,

Normally there is in the watchdog a more specific error, can you provide us that error?

And can you send me (preferable by mail) the key en secret en environment you connecting with? So i can doublecheck they are ok.   

Thanks,

S

**Comment by 30equals** [comment]
Hey Sven,

A colleague of yours already informed me through email about certain functionalities not being fully operational due to a server migration...? 
I'll follow up in this issue as soon as i have more info.
