### ISSUE TITLE
Missing dependency on the culturefeed base module

### ISSUE THREAD

**Issue by Hjarnmastara** [cultuurnet/culturefeed#53]
Hai guys,

The culturefeed_agenda module uses some functions that are defined in the culturefeed.helpers.inc file.
If you don't have the culturefeed module enabled, the culturefeed_agenda will throw an fatal error when it's trying to use the helper function.

Cheers

**Comment by svenhoutmeyers** [comment]
@zuuperman maybe you fixed this in your changes for Herita?

**Comment by zuuperman** [comment]
Hi Hjarnmastara,

I created a new branch based on master with all the changes to remove all the dependencies of culturefeed_search to culturefeed. Can you validate this? When using that branch + latest dev of culturefeed_bootstrap (if you use the theme), all dependency issues should be gone.
