### ISSUE TITLE
Entry API - Recurring events

### ISSUE THREAD

**Issue by JinX-Be** [cultuurnet/culturefeed#58]
It looks like it's not possible to add a recurring event through the entry API.
Is this correct? 
Because it's possible through UITDatabank.
Will this feature be implemented?

![screen shot 2015-09-11 at 2 06 24 pm](https://cloud.githubusercontent.com/assets/10371243/9814431/53b37a42-588e-11e5-8e33-32f03bc8fb59.png)

**Comment by svenhoutmeyers** [comment]
You can add recurring single dates (with + add date) or one period (with + add end date or time). Recurring periods is not possible through UITDatabank indeed.
