### ISSUE TITLE
Only works on 5.5

### ISSUE THREAD

**Issue by yannickonsea** [cultuurnet/culturefeed#59]
The Read me states that PHP5.5 is the minimum requirement for the module to work.
I was working on PHP5.6 and it didn't work. Could not log in with UIT, and thus I could not add any events through the Entry API, and my agenda/search page didn't work either.

Changed my PHP version to 5.5 and everything works now.

**Comment by svenhoutmeyers** [comment]
tested with 5.6.7 for issue 66 and it was no problem
