### ISSUE TITLE
culturefeed_search: ActivityStatsExtendedEntity' not found 

### ISSUE THREAD

**Issue by BertBruggeman** [cultuurnet/culturefeed#66]
Fatal error: Class 'CultuurNet\Search\ActivityStatsExtendedEntity' not found in /var/www/vhosts/e2e.be/boechout.e2e.be/sites/all/modules/culturefeed/culturefeed_search/lib/Drupal/DrupalNodeExtendedEntity.php on line 11

**Comment by svenhoutmeyers** [comment]
Then you use an old version of Search: https://github.com/cultuurnet/Search to latest version. It's documented in the release notes if you have to update the libraries (https://github.com/cultuurnet/culturefeed/releases)

If you use composer with in composer.json the Next Significant Release Operators (https://getcomposer.org/doc/articles/versions.md#tilde) just run 'composer update'.

**Comment by BertBruggeman** [comment]
Downloaded 1h ago? (zip file from git)

**Comment by svenhoutmeyers** [comment]
Cleared registry (drush rr)?

**Comment by BertBruggeman** [comment]
Registry  cleared, still same issue (on a clean drupal 7.40)

**Comment by svenhoutmeyers** [comment]
Forgat require 'vendor/autoload.php'; in settings.php (see https://github.com/cultuurnet/culturefeed)?

**Comment by BertBruggeman** [comment]
nope...

**Comment by svenhoutmeyers** [comment]
And the right Search version is in /vendor/cultuurnet/search? Then my optioned are finished i'm afraid.

**Comment by svenhoutmeyers** [comment]
I think you best double-check if ActivityStatsExtendedEntity is in Search (/vendor/cultuurnet/search/lib/CultuurNet/Search/ActivityStatsExtendedEntity.php), if it is something is wrong with loading the Class in you Drupal module.

**Comment by BertBruggeman** [comment]
- Installed fresh drupal (7.40) with drush (no other contrib modules except registry_rebuild)
- Php version is 5.6 
- cloned culturefeed with git in sites/all/modules
- copied composer.json to root folder & ran composer install
- checked vendor folder
- added require... to settings.php
- enabled culturefeed & culturefeed_agenda

- ran drush rr && drush cc all && drush cron

- still same issue

**Comment by svenhoutmeyers** [comment]
rr is not a drupal module but a drush module, see
https://www.drupal.org/project/registry_rebuild, maybe that's your problem?

2015-10-21 11:03 GMT+02:00 BertBruggeman <notifications@github.com>:

**Comment by BertBruggeman** [comment]
registry_rebuild downloaded and is working... (see above)

**Comment by svenhoutmeyers** [comment]
I don't have time to simulate it now but i can check this friday if you
want, it's a strange thing because with all the things we checked it works
on other installs...

2015-10-21 11:14 GMT+02:00 BertBruggeman <notifications@github.com>:

**Comment by BertBruggeman** [comment]
Ok, could it be the php version (5.6) ?

**Comment by svenhoutmeyers** [comment]
There is this other issue from a wunderkraut developer (
https://github.com/cultuurnet/culturefeed/issues/59) but after a check of
their senior developer (zuuperman) he said to me that 5.6 wasn't the issue,
but i had no time to double-check.

2015-10-21 12:46 GMT+02:00 BertBruggeman <notifications@github.com>:

**Comment by svenhoutmeyers** [comment]
I just installed D7 and culturefeed like you said and after filling in key and secret search (agenda/search) and detail works like a charm 

https://www.dropbox.com/s/l0a8tdz6cspcs46/Screenshot%202015-10-23%2017.36.24.png?dl=0

**Comment by bert-bruggeman** [comment]
Our php version is 5.6.12, the files from /vendor are loaded but the classes like "'CultuurNet\Search\ActivityStatsExtendedEntity" are not...

**Comment by bert-bruggeman** [comment]
Also tried with 5.6.14 (we have no older 5.6 versions to test)

**Comment by bert-bruggeman** [comment]
There was a problem on our sever with our latest plesk panel (our basedir redirected to the wrong place), sorry for the wasted time...

**Comment by svenhoutmeyers** [comment]
ok no problem, glad that you solved it
