### ISSUE TITLE
culturefeed_content hook_field_create_instance adds default values to all new fields

### ISSUE THREAD

**Issue by bert-bruggeman** [cultuurnet/culturefeed#69]
The hook culturefeed_content_field_create_instance should add a default value only to the culturefeed_content field. All new created field instances like an image field can not be saved because a wrong default value... Could be fixed with "if ($instance['widget']['type'] == 'culturefeed_content_default') { ... }

**Comment by svenhoutmeyers** [comment]
Just fixed it, if ok for you we will add it to the 3.7 release. Thanks!

**Comment by svenhoutmeyers** [comment]
Released in https://github.com/cultuurnet/culturefeed/tree/v3.7.0
