### ISSUE TITLE
301 redirects loop

### ISSUE THREAD

**Issue by bregtemundo** [cultuurnet/culturefeed#92]
When in agenda/search as soon as I filter on eg. Type, the url redirects to agenda/doen.

However I the page never loads because I get stuck in an endless redirect loop (301).

When I comment out the redirect rule (see link below) everything seems to work correct.
[culturefeed_agenda.module : line 964](https://github.com/cultuurnet/culturefeed/blob/1a36d1a784bce9c9f88d9d0fc7c35811839c21e1/culturefeed_agenda/culturefeed_agenda.module#L964)

What seems to happen is:
 - the $rewrite is set To true (because agenda/bezoeken != agenda/search )
 - the url is redirected
 - the $rewrite is set To true(because agenda/bezoeken != agenda/search )
 - url is redirected again ...
 - ...

Don't know If it has to do with something set up in our site or that this is a general issue.

**Comment by lukdens** [comment]
Hi @bregtemundo 

This is not the default behaviour of the redirects in the culturefeed_agenda module, as you can see on http://www.culturefeed.be/agenda/bezoeken

It looks like there is a custom URL redirect or alias active on the agenda/search path in your site that is causing the loop. Maybe it's just a matter of ignoring the agenda/search path in the module that is trying to do the additional redirect.

Can you verify this first and let us know when you find something? It can be interesting to know for other developers too.

**Comment by bregtemundo** [comment]
Indeed it was a conflict with another module. In my case it was the https://www.drupal.org/project/menu_trail_by_path module , and more particular it calling the drupal function : 
https://api.drupal.org/api/drupal/includes!path.inc/function/drupal_get_normal_path/7 .
