### ISSUE TITLE
Mobile_detect not found in _culturefeed_agenda_preprocess_agenda

### ISSUE THREAD

**Issue by mallezie** [cultuurnet/culturefeed#93]
Inside the _culturefeed_agenda_preprocess_agenda function the mobile detect helper function is called. This function checks / uses the external Mobile_Detect php class. 
When you don't use this class, the drupal DB log get's filled with class not found notices, generated by the helper function. 
However this external class is not required, and doesn't get added by any composer files. This is good, since it's not needed to use. And this plugin wouldn't work correctly with the drupal page cache. So the actual issue is to not write those messages to the watchdog table.

**Comment by stijnswaanen** [comment]
Hi @mallezie 

we decided shortly to remove all dependencies to the Mobile Detect PHP library and move this detection to our theme culturefeed_bootstrap through javascript. See also PR https://github.com/cultuurnet/culturefeed/pull/142.

This issue should be fixed soon when there is a new release. I hope somewhere in May 2017.
