### ISSUE TITLE
HTTP ERROR 500

### ISSUE THREAD

**Issue by digitw** [cultuurnet/culturefeed#96]
We have a problem with the installation:

**composer diagnose**
Checking composer.json: FAIL
require.mobiledetect/mobiledetectlib : unbound version constraints (dev-master) should be avoided
Checking platform settings: FAIL
The OpenSSL library (0.9.8o) used by PHP does not support TLSv1.2 or TLSv1.1.
If possible you should upgrade OpenSSL to version 1.0.1 or above.

Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: FAIL
You are not running the latest stable version, run `composer self-update` to update (1.0.0 => 1.0.3)

**composer validate**
./composer.json is valid, but with a few warnings
See https://getcomposer.org/doc/04-schema.md for details on the schema
require.mobiledetect/mobiledetectlib : unbound version constraints (dev-master) should be avoided

**composer self-update**
Updating to version 1.0.3.
Downloading: 100%

 [ErrorException]
 rename(/usr/local/bin/composer): failed to open stream: Permission denied

self-update [-r|--rollback] [--clean-backups] [--no-progress] [--update-keys] [--stable] [--preview] [--snapshot] [--] [<version>]

**Comment by svenhoutmeyers** [comment]
Hello, do you have some more info about the error you have?

**Comment by digitw** [comment]
**Composer diagnose**
Checking composer.json: FAIL
require.mobiledetect/mobiledetectlib : unbound version constraints (dev-master) should be avoided
Checking platform settings: FAIL
The OpenSSL library (0.9.8o) used by PHP does not support TLSv1.2 or TLSv1.1.
If possible you should upgrade OpenSSL to version 1.0.1 or above.

**Drupal** : Status report : Install the composer/composer PHP library

**Comment by digitw** [comment]
Solved. There was a conflict with the OAuth/Twitter module.

**Comment by svenhoutmeyers** [comment]
Great, because we didn't recognise this one ;-).
